version: 2

formats:
  - htmlzip
  - epub

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

mkdocs:
  configuration: docs/mkdocs.yml
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt
